//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingCalendarRepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseDetail
    {
        public decimal Course_ID { get; set; }
        public Nullable<decimal> Trainer_ID { get; set; }
        public string Course_Name { get; set; }
        public string Description { get; set; }
        public string Duration { get; set; }
        public System.DateTime Created_On { get; set; }
        public Nullable<System.DateTime> Updated_On { get; set; }
        public Nullable<decimal> Created_By { get; set; }
        public Nullable<decimal> Updated_By { get; set; }
        public byte[] Attachment { get; set; }
        public string File_Name { get; set; }
        public string File_Extension { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
