//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingCalendarRepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollmaster
    {
        public decimal Enrollmaster_ID { get; set; }
        public Nullable<decimal> Trainer_ID { get; set; }
        public decimal Course_ID { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public string Venue { get; set; }
        public System.DateTime Last_date_to_enroll { get; set; }
        public decimal Max_enroll { get; set; }
        public Nullable<decimal> Min_enroll { get; set; }
        public System.DateTime Created_On { get; set; }
        public Nullable<System.DateTime> Updated_On { get; set; }
        public bool Status { get; set; }
    }
}
