//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainingCalendarRepository.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public decimal Enrollment_ID { get; set; }
        public decimal EnrollMaster_ID { get; set; }
        public decimal User_ID { get; set; }
        public System.DateTime Reg_On { get; set; }
        public Nullable<System.DateTime> Unreg_On { get; set; }
        public string Reason_For_Unreg { get; set; }
        public Nullable<System.DateTime> Created_On { get; set; }
        public Nullable<System.DateTime> Updated_On { get; set; }
    
        public virtual UserLogin UserLogin { get; set; }
    }
}
